# Site settings
author: Jeff Brown 
title: Jeff Brown
header-img: img/home-bg.png
email: brownjs03@gmail.com
copyright_name: Jeff Brown 
description: > # this means to ignore newlines until "baseurl:"
  Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brownjs03

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
